spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: authorization_code // OAuth2.0 ???? ??
            client-id: oauth2-client-app // ??? ???? ??? ????? ???
            client-name: oauth2-client-app  // ????? ??
            client-secret: tnl8eYYWfkjabj4f2t // ??? ???? ??? ????? ????
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
            clientAuthenticationMethod: client_secret_post
            scope: openid,email
          provider: ## ??? ??
            keycloak:
              authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth // OAuth2.0??????
              issuer-uri: http://localhost:8080/realms/oauth2

